# -*- coding: utf-8 -*-
"""The Italian names that saves written before schema version 27 still use.

Version 1.0.0 turned the whole codebase to English, storage included: table
and column names, the keys of the kingdom document, the ids of rules data
(skills, ruins, activities, feats, ...) and every enum value. A save written by
an earlier version is translated once, on first open, by
`migrations.upgrade_storage_v27`; a legacy JSON save goes through
`migrations.translate_document`. Both read the maps below.

`DOCUMENT_KEYS` was generated from the map that drove the rename of release
1.0.0 (a one-off tool, no longer in the repository) and only ever matches
**dictionary keys**; the value maps are
applied field by field, so a character called «Lago» keeps its name.
"""

DOCUMENT_KEYS = {
    "_acqua_chiave": "_water_key",
    "_acqua_svg": "_water_svg",
    "_campo_chiave": "_field_key",
    "_campo_json": "_field_json",
    "_fondo": "_ground",
    "_fondo_chiave": "_ground_key",
    "_fonte": "_source",
    "_nota": "_note",
    "_nota_cd": "_dc_note",
    "_nota_elementi_terreno": "_hex_features_note",
    "_nota_esplorazione": "_exploration_note",
    "_note_cd": "_dc_note",
    "_pagina": "_page",
    "_pausa_dei_leader": "_leaders_rest",
    "_turno_di_regno": "_kingdom_turn",
    "_vista": "_view",
    "_vista_chiave": "_view_key",
    "a_bordo": "aboard",
    "ab": "skill",
    "abbandonare_esagono": "abandon_hex",
    "abilita": "skills",
    "abilita_leader": "leader_skills",
    "abilita_note": "skills_note",
    "accordi": "agreements",
    "accordi_commerciali": "trade_agreements",
    "acqua": "water",
    "acqua_campioni": "water_samples",
    "acqua_e_volo": "water_and_flight",
    "acque": "waters",
    "acque_attive": "waters_active",
    "acquistare_prodotti": "purchase_commodities",
    "addestramento_abilita": "skill_training",
    "addestrare_esercito": "train_army",
    "addestrato": "trained",
    "affari_clandestini": "clandestine_business",
    "aggiornato_il": "updated_at",
    "agricoltura": "agriculture",
    "al_buio": "in_the_dark",
    "al_ritrovo": "at_meeting_point",
    "alcuni": "some",
    "altezza_img": "img_height",
    "altre_attivita": "other_activities",
    "amministratore": "admin",
    "andare_a_pesca": "go_fishing",
    "anno": "year",
    "annullato": "cancelled",
    "anteprima_giocatore": "player_preview",
    "aperto": "open",
    "applica_cursore": "apply_slider",
    "archi": "arcs",
    "aria": "air",
    "arrivo": "arrival",
    "arrivo_dove": "arrival_pos",
    "arti": "arts",
    "assente": "absent",
    "assicurazione_regno": "kingdom_assurance",
    "assoldare_avventurieri": "hire_adventurers",
    "atomi": "atoms",
    "attende": "waiting",
    "attenzione_assoluta": "focused_attention",
    "attesa": "wait",
    "attingere_tesoreria": "tap_treasury",
    "attivita": "activities",
    "attivita_al_giorno": "activities_per_day_table",
    "attivita_extra": "extra_activities",
    "attivita_giorno": "activities_per_day",
    "attivita_turno": "turn_activities",
    "attivo": "active",
    "aumenti": "boosts",
    "aumenti_finali": "final_boosts",
    "aumento": "boost",
    "azioni": "actions",
    "azzardo_offensivo": "offensive_gambit",
    "azzera_regno": "reset_kingdom",
    "barca": "boat",
    "barra_nebbia": "fog_bar",
    "battito": "heartbeat",
    "bersaglio": "target",
    "bisestile": "leap_year",
    "bloccata": "blocked",
    "bonus_livello": "level_bonus",
    "bonus_max_fama": "fame_bonus_max",
    "bonus_oggetto": "item_bonus",
    "bonus_oggetto_max": "item_bonus_max",
    "bonus_velocita_m": "speed_bonus_m",
    "bordo": "edge",
    "bottone_acque": "water_button",
    "bottone_icone": "icons_button",
    "bottone_viaggio": "travel_button",
    "bussola": "compass",
    "cammino": "course",
    "cammino_a_tappe": "path_by_waypoints",
    "campagna_id": "campaign_id",
    "campi_nascosti": "hidden_fields",
    "campo": "field",
    "capacita": "capabilities",
    "capi": "ends",
    "capitale": "capital",
    "car": "ability",
    "caratteristica": "ability",
    "caratteristiche": "abilities",
    "carica_immagine": "upload_image",
    "carta": "chart",
    "categoria": "category",
    "categorie": "categories",
    "cavarsela": "muddle_through",
    "cd": "dc",
    "cd_controllo": "control_dc",
    "cd_evento": "event_dc",
    "cd_mod": "dc_mod",
    "celebrare_festivita": "celebrate_holiday",
    "cella": "cell",
    "celle": "cells",
    "cento_pr": "rp_100",
    "centro": "center",
    "chi": "who",
    "cibo": "food",
    "citta": "city",
    "civica": "civic",
    "collina": "hills",
    "collina_pianura": "hill_or_plain",
    "collisione": "collision",
    "colonne": "columns",
    "colore": "color",
    "colore_giocatore": "player_color",
    "commerciare_prodotti": "trade_commodities",
    "commercio": "trade",
    "commercio_interno": "insider_trading",
    "compagnia": "party",
    "competenza": "proficiency",
    "competenza_minima": "min_proficiency",
    "competenze": "proficiencies",
    "comune": "common",
    "concessione": "charter",
    "concessione_libero": "charter_free_boost",
    "concessioni": "charters",
    "concluso": "completed",
    "confine": "border",
    "confini": "borders",
    "conflitto": "strife",
    "congedare_esercito": "disband_army",
    "conquista": "conquest",
    "consigliere": "counselor",
    "consumo": "consumption",
    "consumo_eserciti": "army_consumption",
    "consumo_extra": "consumption_extra",
    "contati": "counted",
    "conteggi": "counts",
    "controllo": "control",
    "corrente": "current",
    "corrente_da": "current_from",
    "correnti": "currents",
    "corruzione": "corruption",
    "costeggiare": "coast_along",
    "costi": "costs",
    "costo": "cost",
    "costo_attivita": "activity_cost",
    "costo_dati": "cost_data",
    "costo_pr": "rp_cost",
    "costo_raw": "cost_raw",
    "costo_terreno_sconnesso": "disconnected_terrain_cost",
    "costo_totale": "total_cost",
    "costruire_strade": "build_roads",
    "costruire_struttura": "build_structure",
    "costruzione": "construction",
    "creare_capolavoro": "create_a_masterpiece",
    "creata_il": "created_at",
    "creato": "created",
    "creato_da": "created_by",
    "creato_il": "created_at",
    "crimine": "crime",
    "cultura": "culture",
    "cursore_viaggio": "travel_slider",
    "da": "from",
    "dadi_bonus": "bonus_dice",
    "dadi_penalita": "penalty_dice",
    "dado": "die",
    "dado_risorsa": "resource_die",
    "dalla_tabella": "from_table",
    "decadenza": "decay",
    "deciso": "decided",
    "demolire": "demolish",
    "descrizione": "description",
    "destinatario": "recipient",
    "dettaglio": "detail",
    "deve_cambiare_pw": "must_change_pw",
    "difesa": "defense",
    "difetto": "flaw",
    "difficile": "difficult",
    "difficolta": "difficulty",
    "difficolta_gm": "gm_difficulty",
    "dimensione_10": "size_10",
    "dimensione_100": "size_100",
    "dimensione_25": "size_25",
    "dimensione_50": "size_50",
    "dimensione_esagono": "hex_size",
    "disegna": "draw",
    "disponibile": "available",
    "disporre_esercito": "deploy_army",
    "dispotismo": "despotism",
    "distintivo": "badge",
    "documento": "document",
    "dopo": "after",
    "dove": "where",
    "dove_x": "pos_x",
    "dove_y": "pos_y",
    "economia": "economy",
    "effetti": "effects",
    "effetti_regno": "kingdom_effects",
    "elementi": "features",
    "elementi_nascosti": "hidden_features",
    "elementi_terreno": "hex_features",
    "elemento": "feature",
    "emissario": "emissary",
    "equipaggiare_esercito": "outfit_army",
    "equipaggio": "crew",
    "esagoni": "hexes",
    "esagoni_visibili": "visible_hexes",
    "esagono": "hexagon",
    "eserciti": "armies",
    "esercito": "army",
    "esiti": "outcomes",
    "espansione": "expansion",
    "esperto": "expert",
    "esplorazione": "exploration",
    "esporta_salvataggio": "export_save",
    "est": "east",
    "etichette": "labels",
    "eventi": "events",
    "evento": "event",
    "fabbricare_oggetti_lusso": "craft_luxuries",
    "fallimento": "failure",
    "fallimento_critico": "critical_failure",
    "fama": "fame",
    "fama_fortuna": "fame_and_fortune",
    "fare_il_raccolto": "harvest_crops",
    "fase": "phase",
    "fase_corrente": "current_phase",
    "fasi_turno": "turn_phases",
    "fattorie": "farms",
    "fermo": "still",
    "feudalesimo": "feudalism",
    "feudi_fortificati": "fortified_fiefs",
    "finanziamento": "grant",
    "fino_a": "up_to",
    "fisso": "fixed",
    "fiume": "river",
    "fonte": "source",
    "foresta": "forest",
    "foresta_palude": "forest_or_swamp",
    "formato": "format",
    "fortificare_accampamento": "fortify_camp",
    "fortificare_esagono": "fortify_hex",
    "fortificato": "fortified",
    "fortificazione": "fortification",
    "fra_le_righe": "between_the_lines",
    "generale": "general",
    "gestire_accordi": "manage_trade_agreements",
    "gestisci_personaggi": "manage_characters",
    "gestisci_stalla": "manage_stable",
    "gestisci_utenti": "manage_users",
    "giocatore": "player",
    "giorni": "days",
    "giorni_pausa_leader": "leader_rest_days",
    "giorni_settimana": "weekdays",
    "giorni_sostenibili": "sustainable_days",
    "giorno": "day",
    "giorno_partenza": "departure_day",
    "girati": "turned",
    "girato": "turned_one",
    "giuramento_fedelta": "pledge_of_fealty",
    "governa_tempo": "control_clock",
    "governante": "ruler",
    "governare": "statecraft",
    "governi": "governments",
    "governo": "government",
    "governo_collaborativo": "cooperative_leadership",
    "governo_libero": "government_free_boost",
    "grafo": "graph",
    "griglia": "grid",
    "griglie": "grids",
    "gruppi": "groups",
    "gruppo": "group",
    "guada": "wade",
    "guado": "ford",
    "guardiano": "warden",
    "guarire_esercito": "recover_army",
    "guerra": "warfare",
    "ha_ponte": "has_bridge",
    "hash_pw": "pw_hash",
    "hex_riga": "hex_row",
    "icona": "icon",
    "ignora": "ignore",
    "ignoti": "unknowns",
    "ignoto": "unknown_",
    "immagine": "image",
    "in_corso": "in_progress",
    "in_lago": "in_lake",
    "incroci": "crossings_",
    "industria": "industry",
    "infamia": "infamy",
    "infiltrarsi": "infiltration",
    "influenza": "influence",
    "ingegneria": "engineering",
    "ingresso": "entry",
    "inizio": "start",
    "insediamenti": "settlements",
    "insediamento": "settlement",
    "insediamento_indip": "freehold",
    "insieme": "together",
    "intero": "whole",
    "intrattenimento_ispiratore": "inspiring_entertainment",
    "intrigo": "intrigue",
    "investimento_capitali": "capital_investment",
    "investiti": "invested_count",
    "investito": "invested",
    "inviare_delegato": "send_diplomatic_envoy",
    "irraggiungibile": "unreachable",
    "irrigare": "irrigation",
    "isolati": "blocks",
    "isolati_attivi": "active_blocks",
    "isolati_costruiti": "built_blocks",
    "isolato": "block",
    "iterazioni": "iterations",
    "km_giorno": "km_day",
    "km_ora": "km_hour",
    "laghi": "lakes",
    "lago": "lake",
    "lago_fiume": "lake_or_river",
    "lago_id": "lake_id",
    "lago_punti": "lake_points",
    "larghezza_img": "img_width",
    "larghezza_km": "width_km",
    "lati": "sides",
    "lato": "side",
    "lato_a": "side_a",
    "lato_b": "side_b",
    "lealta": "loyalty",
    "leggendario": "legendary",
    "legname": "lumber",
    "libera": "open_charter",
    "liberare": "clear",
    "liberare_esagono": "clear_hex",
    "liberato": "cleared",
    "libere_eque": "free_and_fair",
    "liberi": "free",
    "limite_turno": "turn_limit",
    "liquidare_risorse": "liquidate_resources",
    "livello": "level",
    "livello_gruppo": "party_level",
    "livello_regno": "kingdom_level",
    "lotti": "lots",
    "lusso": "luxuries",
    "maestro": "master",
    "magazzino": "storage",
    "magazzino_extra": "storage_extra",
    "magia": "magic",
    "magia_pratica": "practical_magic",
    "malcontento": "unrest",
    "mancanti": "missing",
    "mappa": "map",
    "mappare_area": "map_the_area",
    "marcia_forzata": "forced_march",
    "maschere": "masks",
    "mese": "month",
    "mesi": "months",
    "metri": "metres",
    "metri_al_minuto": "metres_per_minute",
    "metropoli": "metropolis",
    "mezzo": "vehicle",
    "migliora_di_gradi": "improves_by_steps",
    "miglioramento_a": "upgrade_to",
    "miglioramento_di": "upgrade_of",
    "migliorare_stile_vita": "improve_lifestyle",
    "miliari": "milestones",
    "minerali": "ore",
    "miniature": "thumbnails",
    "mod_costituzione": "con_mod",
    "modifica_regno": "edit_kingdom",
    "modificatori": "modifiers",
    "modo_acqua": "water_mode",
    "modo_confine": "border_mode",
    "modo_nebbia": "fog_mode",
    "modo_viaggio": "travel_mode",
    "montagna": "mountains",
    "montagna_rovine": "mountain_or_ruin",
    "monte": "upstream",
    "mosso": "moved",
    "mostra_confini": "show_borders",
    "mostra_griglia": "show_grid",
    "mostra_icone": "show_icons",
    "mostra_viaggi": "show_journeys",
    "motivo": "reason",
    "mura": "walls",
    "nascondi": "hide",
    "nautica": "boating",
    "nebbia": "fog",
    "nebbia_opacita": "fog_opacity",
    "nessuna": "none_",
    "nodi": "nodes",
    "nome": "name",
    "nome_utente": "username",
    "nord": "north",
    "nota": "note",
    "note_gm": "gm_notes",
    "nuotare": "swim",
    "nuoto": "swim",
    "nuova_direzione": "new_leadership",
    "occupati": "occupied",
    "offrire_assistenza": "provide_care",
    "ogni_anni": "every_years",
    "oligarchia": "oligarchy",
    "oltre": "beyond",
    "opzioni": "options",
    "ordine": "order",
    "ordine_categorie": "category_order",
    "ore_al_giorno": "hours_per_day",
    "orientamento": "orientation",
    "origine": "origin",
    "otto_ruoli": "all_eight_leaders",
    "ovest": "west",
    "paese": "town",
    "palude": "swamp",
    "parita": "tie",
    "partenza": "departure",
    "passa": "passes",
    "passeggeri": "passengers",
    "passi": "steps",
    "passo": "step",
    "pe": "xp",
    "pe_miliare": "milestone_xp",
    "pe_miliari": "milestone_xp",
    "pedaggio": "toll",
    "penalita": "penalty",
    "penalita_assenza": "absence_penalty",
    "per_fiume": "by_river",
    "percorso": "path",
    "personaggi": "characters",
    "personaggi_su": "characters_on",
    "personaggio_id": "character_id",
    "persone": "people",
    "pezzo": "piece",
    "pg": "pc",
    "pianifica_viaggio": "plan_travel",
    "piano": "plan",
    "pianura": "plains",
    "pids": "char_ids",
    "pietra": "stone",
    "pilota": "pilot",
    "pilotaggio": "piloting",
    "politica": "politics",
    "ponte": "bridge",
    "ponti": "crossings",
    "popolazione": "population",
    "posiziona": "place",
    "posiziona_pg": "place_pc",
    "posiziona_veicolo": "place_vehicle",
    "possibile": "possible",
    "posti": "seats",
    "pr": "rp",
    "pr_spesi_turno": "rp_spent_turn",
    "prefisso": "prefix",
    "prerequisiti": "prerequisites",
    "presidiare_esercito": "garrison_army",
    "prezzo": "price",
    "prima_citta": "first_city",
    "prima_metropoli": "first_metropolis",
    "prima_relazione": "first_diplomatic_relation",
    "primo_accordo": "first_trade_agreement",
    "primo_paese": "first_town",
    "primo_punto_riferimento": "first_landmark",
    "primo_rifugio": "first_refuge",
    "primo_villaggio": "first_village",
    "prodotti": "commodities",
    "prodotto": "commodity",
    "prodotto_scelta": "commodity_choice",
    "progresso": "progress",
    "pronosticare": "prognostication",
    "pronto": "ready",
    "proposta_acque": "water_proposal",
    "proprietari": "owners",
    "proprio_personaggio": "own_character",
    "prova": "check",
    "pubblico": "public",
    "punti": "points",
    "punti_fama": "fame_points",
    "punto": "point",
    "punto_riferimento": "landmark",
    "puo_vedere": "can_see",
    "qualita_vita": "quality_of_life",
    "quando": "logged_at",
    "quantita": "quantity",
    "raddoppiato": "doubled",
    "radunare_bestiame": "gather_livestock",
    "raduno": "rendezvous",
    "rami": "branches",
    "rarita": "rarity",
    "reclutare_esercito": "recruit_army",
    "recupero_rapido": "quick_recovery",
    "regia": "gm_screen",
    "regione": "region",
    "registro": "log",
    "regno": "kingdom",
    "relazioni": "diplomatic_relations",
    "repubblica": "republic",
    "reputazione": "reputation",
    "requisiti": "requirements",
    "residenziali": "residential_count",
    "rete": "network",
    "rete_chiave": "network_key",
    "richiedere_aiuto_estero": "request_foreign_aid",
    "ricognito": "reconnoitered",
    "ricognizione": "reconnaissance",
    "rifugio": "refuge",
    "riga": "row",
    "riga_a": "row_a",
    "riga_b": "row_b",
    "righe": "rows",
    "rimando": "reference",
    "rimboccarsi_maniche": "pull_together",
    "riparare_reputazione": "repair_reputation",
    "ripetibile": "repeatable",
    "riposare_rilassarsi": "rest_and_relax",
    "riquadro": "box",
    "riscuotere_tasse": "collect_taxes",
    "risoluzione": "resolution",
    "risorsa": "resource",
    "risorse": "resources",
    "ritratto": "portrait",
    "riva": "bank",
    "rive": "banks",
    "rivela": "reveal",
    "rivelato_il": "revealed_at",
    "rivendicare": "claim",
    "rivendicare_esagono": "claim_hex",
    "rivendicato": "claimed",
    "rotta": "route",
    "rovina": "ruin",
    "rovina_scelta": "ruin_choice",
    "rovine": "ruins",
    "rovine_elem": "ruins_feature",
    "ruoli": "roles",
    "ruolo": "role",
    "sbarco": "landing",
    "scadenza": "expiry",
    "scala": "scale",
    "scalare": "scalable",
    "scegli": "choose",
    "scheda": "tab",
    "schiacciare_dissenso": "crush_dissent",
    "sconosciuto": "unknown",
    "secondi_per_giorno": "seconds_per_day",
    "sedare_malcontento": "quell_unrest",
    "segno": "sign",
    "selezione_nebbia": "fog_selection",
    "senza_addestramento": "untrained",
    "senza_verso": "without_direction",
    "separati": "separate",
    "servizio_civile": "civil_service",
    "sezioni": "sections",
    "sezioni_chiave": "sections_key",
    "singoli": "singles",
    "sito_lavoro": "work_site",
    "smarrito": "lost",
    "soglia": "threshold",
    "soglie_malcontento": "unrest_thresholds",
    "solo_acqua": "water_only",
    "solo_costruibili": "buildable_only",
    "soluzione_creativa": "creative_solution",
    "soluzione_sovrannaturale": "supernatural_solution",
    "sommario": "summary",
    "sopra": "at",
    "sopra_x": "at_x",
    "sopra_y": "at_y",
    "sopravvivere": "subsist",
    "sopravvivere_anarchia": "endure_anarchy",
    "sosta": "halt",
    "sovrappopolato": "overcrowded",
    "spazio": "space",
    "speciale": "special",
    "spese": "expenses",
    "spettatore": "spectator",
    "sponda": "shore",
    "sponde": "shores",
    "stabilire_accordo_commerciale": "establish_trade_agreement",
    "stabilire_insediamento": "establish_settlement",
    "stabilire_sito_lavoro": "establish_work_site",
    "stabilire_terreno_agricolo": "establish_farmland",
    "stabilita": "stability",
    "stalla_id": "stable_id",
    "stati": "statuses",
    "stato": "status",
    "strade": "roads",
    "struttura": "structure",
    "studio": "scholarship",
    "successo": "success",
    "successo_critico": "critical_success",
    "sud": "south",
    "superiore": "greater_difficult",
    "tabella": "table",
    "tabella_dimensione": "size_table",
    "tabella_livelli": "level_table",
    "taglia": "size",
    "taglio_in_corso": "cut_in_progress",
    "talenti": "feats",
    "talento": "feat",
    "tappa": "waypoint",
    "tappe": "waypoints",
    "tappe_stati": "waypoint_statuses",
    "tasse": "taxes",
    "taumocrazia": "thaumocracy",
    "tavolo": "table",
    "tempo": "clock",
    "terra": "land",
    "terre_selvagge": "wilderness",
    "terreni": "terrains",
    "terreno": "terrain",
    "terreno_agricolo": "farmland",
    "terrestre": "land_",
    "territori_centrali": "heartlands",
    "territorio": "territory",
    "territorio_centrale": "heartland",
    "tesoriere": "treasurer",
    "testo": "text",
    "tipi": "kinds",
    "tipi_insediamento": "settlement_types",
    "tipo": "kind",
    "titolo": "title",
    "tocca": "touch",
    "togli_verso": "remove_direction",
    "tolti": "removed",
    "tolto": "removed_one",
    "totale": "total",
    "tracce": "traces",
    "tracciato": "traced",
    "traino": "towing",
    "trappola": "trap",
    "trasferire_capitale": "relocate_capital",
    "tratte": "legs",
    "tratti": "stretches",
    "tratti_atomi": "atom_stretches",
    "tratti_struttura": "structure_traits",
    "tratto": "stretch",
    "tratto_struttura": "structure_trait",
    "turno": "turn",
    "turno_creato": "turn_created",
    "turno_iniziato_il": "turn_started_at",
    "turno_risolto": "turn_resolved",
    "ultimo": "last",
    "ultimo_accesso": "last_login",
    "ultimo_noto": "last_known",
    "unione": "union",
    "utente": "user",
    "utente_id": "user_id",
    "utente_rev": "user_rev",
    "utenti": "users",
    "valle": "downstream",
    "vecchie": "old_ones",
    "vecchio": "old",
    "vedi_segreti": "see_secrets",
    "veicoli": "vehicles",
    "veicolo": "vehicle",
    "velo_terreni": "terrain_veil",
    "velocita": "speed",
    "velocita_di_viaggio": "travel_speed",
    "velocita_dipende_da": "speed_depends_on",
    "velocita_gruppo": "party_speed",
    "velocita_m": "speed_m",
    "velocita_nuoto_m": "swim_speed_m",
    "velocita_testo": "speed_text",
    "versi": "directions",
    "versione": "version",
    "viaggiatori": "travellers",
    "viaggio": "travel",
    "viaggio_pg": "travel_pcs",
    "viaggio_scelto": "chosen_journey",
    "viaggio_veicolo": "travel_vehicle",
    "vic": "nb",
    "vicere": "viceroy",
    "vicini": "neighbours",
    "villaggio": "village",
    "viva": "live",
    "voce": "entry",
    "volare": "fly",
    "vuote": "empty_ones",
}

HEX_STATUS = {
    "sconosciuto": "unknown",
    "ricognito": "reconnoitered",
    "liberato": "cleared",
    "rivendicato": "claimed",
}

TERRAINS = {
    "pianura": "plains",
    "collina": "hills",
    "foresta": "forest",
    "palude": "swamp",
    "montagna": "mountains",
    "lago": "lake",
    "fiume": "river",
    "rovine": "ruins",
}

FEATURE_KINDS = {
    "insediamento": "settlement",
    "insediamento_indip": "freehold",
    "ponte": "bridge",
    "punto_riferimento": "landmark",
    "rifugio": "refuge",
    "risorsa": "resource",
    "rovine_elem": "ruins_feature",
    "sito_lavoro": "work_site",
    "struttura": "structure",
    "terreno_agricolo": "farmland",
    "fortificazione": "fortification",
    "strade": "roads",
    "trappola": "trap",
    "dungeon": "dungeon",
    "evento": "event",
}

HIDDEN_FIELDS = {
    "strade": "roads",
    "fortificato": "fortified",
    "terreno_agricolo": "farmland",
    "sito_lavoro": "work_site",
    "insediamento": "settlement",
    "nome": "name",
    "stato": "status",
    "terreni": "terrains",
    "elementi": "features",
}

DIFFICULTIES = {
    "aperto": "open",
    "difficile": "difficult",
    "superiore": "greater_difficult",
}

USER_ROLES = {
    "amministratore": "admin",
    "giocatore": "player",
    "spettatore": "spectator",
}

VEHICLE_KINDS = {
    "terra": "land",
    "acqua": "water",
    "aria": "air",
}

JOURNEY_STATUS = {
    "in_corso": "in_progress",
    "concluso": "completed",
    "annullato": "cancelled",
}

BORDER_KINDS = {
    "acqua": "water",
    "guado": "ford",
    "ponte": "bridge",
}

SOURCES = {
    "carta": "chart",
    "tracciato": "traced",
    "tavolo": "table",
}

LOG_CATEGORIES = {
    "mappa": "map",
    "insediamento": "settlement",
    "prova": "check",
    "malcontento": "unrest",
    "rovina": "ruin",
    "consumo": "consumption",
    "pe": "xp",
    "regno": "kingdom",
    "turno": "turn",
    "risorse": "resources",
    "attivita": "activities",
    "evento": "event",
}

ABILITY_IDS = {
    "cultura": "culture",
    "economia": "economy",
    "lealta": "loyalty",
    "stabilita": "stability",
}

RUIN_IDS = {
    "corruzione": "corruption",
    "crimine": "crime",
    "decadenza": "decay",
    "conflitto": "strife",
}

SKILL_IDS = {
    "agricoltura": "agriculture",
    "arti": "arts",
    "commercio": "trade",
    "difesa": "defense",
    "esplorazione": "exploration",
    "folklore": "folklore",
    "governare": "statecraft",
    "guerra": "warfare",
    "industria": "industry",
    "ingegneria": "engineering",
    "intrigo": "intrigue",
    "magia": "magic",
    "nautica": "boating",
    "politica": "politics",
    "studio": "scholarship",
    "terre_selvagge": "wilderness",
}

PROFICIENCY_IDS = {
    "senza_addestramento": "untrained",
    "addestrato": "trained",
    "esperto": "expert",
    "maestro": "master",
    "leggendario": "legendary",
}

ROLE_IDS = {
    "governante": "ruler",
    "consigliere": "counselor",
    "emissario": "emissary",
    "generale": "general",
    "guardiano": "warden",
    "maestro": "magister",
    "tesoriere": "treasurer",
    "vicere": "viceroy",
}

COMMODITY_IDS = {
    "cibo": "food",
    "legname": "lumber",
    "lusso": "luxuries",
    "minerali": "ore",
    "pietra": "stone",
}

CHARTER_IDS = {
    "conquista": "conquest",
    "espansione": "expansion",
    "esplorazione": "exploration",
    "finanziamento": "grant",
    "libera": "open_charter",
}

HEARTLAND_IDS = {
    "collina_pianura": "hill_or_plain",
    "foresta_palude": "forest_or_swamp",
    "lago_fiume": "lake_or_river",
    "montagna_rovine": "mountain_or_ruin",
}

GOVERNMENT_IDS = {
    "dispotismo": "despotism",
    "feudalesimo": "feudalism",
    "oligarchia": "oligarchy",
    "repubblica": "republic",
    "taumocrazia": "thaumocracy",
    "yeomanry": "yeomanry",
}

PHASE_IDS = {
    "gestione": "upkeep",
    "commercio": "commerce",
    "attivita": "activity",
    "eventi": "event",
}

REPUTATION = {
    "fama": "fame",
    "infamia": "infamy",
}

SETTLEMENT_TYPES = {
    "villaggio": "village",
    "paese": "town",
    "citta": "city",
    "metropoli": "metropolis",
}

COMPASS = {
    "nord": "north",
    "est": "east",
    "sud": "south",
    "ovest": "west",
}

SIDE_KINDS = {
    "terra": "land",
    "acqua": "water",
}

FEAT_IDS = {
    "addestramento_abilita": "skill_training",
    "assicurazione_regno": "kingdom_assurance",
    "cavarsela": "muddle_through",
    "commercio_interno": "insider_trading",
    "feudi_fortificati": "fortified_fiefs",
    "governo_collaborativo": "cooperative_leadership",
    "magia_pratica": "practical_magic",
    "rimboccarsi_maniche": "pull_together",
    "schiacciare_dissenso": "crush_dissent",
    "servizio_civile": "civil_service",
    "intrattenimento_ispiratore": "inspiring_entertainment",
    "liquidare_risorse": "liquidate_resources",
    "recupero_rapido": "quick_recovery",
    "sopravvivere_anarchia": "endure_anarchy",
    "libere_eque": "free_and_fair",
    "qualita_vita": "quality_of_life",
    "fama_fortuna": "fame_and_fortune",
}

MILESTONE_IDS = {
    "primo_punto_riferimento": "first_landmark",
    "primo_rifugio": "first_refuge",
    "primo_villaggio": "first_village",
    "dimensione_10": "size_10",
    "prima_relazione": "first_diplomatic_relation",
    "primo_paese": "first_town",
    "otto_ruoli": "all_eight_leaders",
    "dimensione_25": "size_25",
    "primo_accordo": "first_trade_agreement",
    "prima_citta": "first_city",
    "dimensione_50": "size_50",
    "cento_pr": "rp_100",
    "prima_metropoli": "first_metropolis",
    "dimensione_100": "size_100",
}

ACTIVITY_IDS = {
    "nuova_direzione": "new_leadership",
    "riscuotere_tasse": "collect_taxes",
    "attingere_tesoreria": "tap_treasury",
    "migliorare_stile_vita": "improve_lifestyle",
    "commerciare_prodotti": "trade_commodities",
    "gestire_accordi": "manage_trade_agreements",
    "acquistare_prodotti": "purchase_commodities",
    "affari_clandestini": "clandestine_business",
    "assoldare_avventurieri": "hire_adventurers",
    "attenzione_assoluta": "focused_attention",
    "celebrare_festivita": "celebrate_holiday",
    "creare_capolavoro": "create_a_masterpiece",
    "fabbricare_oggetti_lusso": "craft_luxuries",
    "giuramento_fedelta": "pledge_of_fealty",
    "infiltrarsi": "infiltration",
    "investimento_capitali": "capital_investment",
    "inviare_delegato": "send_diplomatic_envoy",
    "offrire_assistenza": "provide_care",
    "pronosticare": "prognostication",
    "reclutare_esercito": "recruit_army",
    "richiedere_aiuto_estero": "request_foreign_aid",
    "riparare_reputazione": "repair_reputation",
    "riposare_rilassarsi": "rest_and_relax",
    "sedare_malcontento": "quell_unrest",
    "soluzione_creativa": "creative_solution",
    "soluzione_sovrannaturale": "supernatural_solution",
    "stabilire_accordo_commerciale": "establish_trade_agreement",
    "trasferire_capitale": "relocate_capital",
    "abbandonare_esagono": "abandon_hex",
    "andare_a_pesca": "go_fishing",
    "costruire_strade": "build_roads",
    "fare_il_raccolto": "harvest_crops",
    "fortificare_esagono": "fortify_hex",
    "irrigare": "irrigation",
    "liberare_esagono": "clear_hex",
    "radunare_bestiame": "gather_livestock",
    "rivendicare_esagono": "claim_hex",
    "stabilire_terreno_agricolo": "establish_farmland",
    "stabilire_insediamento": "establish_settlement",
    "stabilire_sito_lavoro": "establish_work_site",
    "costruire_struttura": "build_structure",
    "demolire": "demolish",
    "addestrare_esercito": "train_army",
    "azzardo_offensivo": "offensive_gambit",
    "congedare_esercito": "disband_army",
    "disporre_esercito": "deploy_army",
    "equipaggiare_esercito": "outfit_army",
    "guarire_esercito": "recover_army",
    "presidiare_esercito": "garrison_army",
}
